//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dukebox.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public long id { get; set; }
        public string filename { get; set; }
        public string title { get; set; }
        public Nullable<long> lengthInSeconds { get; set; }
        public Nullable<long> albumId { get; set; }
        public Nullable<long> artistId { get; set; }
    }
}
